import * as Font from "expo-font";

export default useFonts = async () =>
  await Font.loadAsync({
    //Inter Fonts
    "Inter-Regular": require("../src/fonts/inter/Inter-Regular.ttf"),
    "Inter-Medium": require("../src/fonts/inter/Inter-Medium.ttf"),
    "Inter-Bold": require("../src/fonts/inter/Inter-Bold.ttf"),
    "Inter-SemiBold": require("../src/fonts/inter/Inter-SemiBold.ttf"),
    "Inter-Black": require("../src/fonts/inter/Inter-Black.ttf"),
    "Inter-ExtraBold": require("../src/fonts/inter/Inter-ExtraBold.ttf"),
    "Inter-ExtraLight": require("../src/fonts/inter/Inter-ExtraLight.ttf"),
    "Inter-Light": require("../src/fonts/inter/Inter-Light.ttf"),
    "Inter-Thin": require("../src/fonts/inter/Inter-Thin.ttf"),

    //Open Sans
    "OpenSans-Regular": require("../src/fonts/opensans/OpenSans-Regular.ttf"),
    "OpenSans-BoldItalic": require("../src/fonts/opensans/OpenSans-BoldItalic.ttf"),
    "OpenSans_Condensed-SemiBoldItalic": require("../src/fonts/opensans/OpenSans_Condensed-SemiBoldItalic.ttf"),
    "OpenSans_SemiCondensed-BoldItalic": require("../src/fonts/opensans/OpenSans_SemiCondensed-BoldItalic.ttf"),
    "OpenSans-Bold": require("../src/fonts/opensans/OpenSans-Bold.ttf"),
    "OpenSans_Condensed-SemiBold": require("../src/fonts/opensans/OpenSans_Condensed-SemiBold.ttf"),
    "OpenSans_SemiCondensed-Bold": require("../src/fonts/opensans/OpenSans_SemiCondensed-Bold.ttf"),
    "OpenSans_Condensed-BoldItalic": require("../src/fonts/opensans/OpenSans_Condensed-BoldItalic.ttf"),
    "OpenSans-ExtraBoldItalic": require("../src/fonts/opensans/OpenSans-ExtraBoldItalic.ttf"),
    "OpenSans_SemiCondensed-ExtraBoldItalic": require("../src/fonts/opensans/OpenSans_SemiCondensed-ExtraBoldItalic.ttf"),
    "OpenSans_Condensed-ExtraBold": require("../src/fonts/opensans/OpenSans_Condensed-ExtraBold.ttf"),
    "OpenSans-ExtraBold": require("../src/fonts/opensans/OpenSans-ExtraBold.ttf"),
    "OpenSans-Italic": require("../src/fonts/opensans/OpenSans-Italic.ttf"),
    "OpenSans_SemiCondensed-Italic": require("../src/fonts/opensans/OpenSans_SemiCondensed-Italic.ttf"),
    "OpenSans_Condensed-Italic": require("../src/fonts/opensans/OpenSans_Condensed-Italic.ttf"),
    "OpenSans-LightItalic": require("../src/fonts/opensans/OpenSans-LightItalic.ttf"),
    "OpenSans_SemiCondensed-LightItalic": require("../src/fonts/opensans/OpenSans_SemiCondensed-LightItalic.ttf"),
    "OpenSans_Condensed-LightItalic": require("../src/fonts/opensans/OpenSans_Condensed-LightItalic.ttf"),
    "OpenSans-Light": require("../src/fonts/opensans/OpenSans-Light.ttf"),
    "OpenSans_SemiCondensed-Light": require("../src/fonts/opensans/OpenSans_SemiCondensed-Light.ttf"),
    "OpenSans_Condensed-Light": require("../src/fonts/opensans/OpenSans_Condensed-Light.ttf"),
    "OpenSans-MediumItalic": require("../src/fonts/opensans/OpenSans-MediumItalic.ttf"),
    "OpenSans_SemiCondensed-MediumItalic": require("../src/fonts/opensans/OpenSans_SemiCondensed-MediumItalic.ttf"),
    "OpenSans_Condensed-MediumItalic": require("../src/fonts/opensans/OpenSans_Condensed-MediumItalic.ttf"),
    "OpenSans-Medium": require("../src/fonts/opensans/OpenSans-Medium.ttf"),
    "OpenSans_SemiCondensed-Medium": require("../src/fonts/opensans/OpenSans_SemiCondensed-Medium.ttf"),
    "OpenSans_Condensed-Medium": require("../src/fonts/opensans/OpenSans_Condensed-Medium.ttf"),
    "OpenSans-Regular": require("../src/fonts/opensans/OpenSans-Regular.ttf"),
    "OpenSans_SemiCondensed-Regular": require("../src/fonts/opensans/OpenSans_SemiCondensed-Regular.ttf"),
    "OpenSans_Condensed-Regular": require("../src/fonts/opensans/OpenSans_Condensed-Regular.ttf"),
    "OpenSans-SemiBoldItalic": require("../src/fonts/opensans/OpenSans-SemiBoldItalic.ttf"),
    "OpenSans_SemiCondensed-SemiBoldItalic": require("../src/fonts/opensans/OpenSans_SemiCondensed-SemiBoldItalic.ttf"),
    "OpenSans_Condensed-SemiBold": require("../src/fonts/opensans/OpenSans_Condensed-SemiBold.ttf"),
    "OpenSans-SemiBold": require("../src/fonts/opensans/OpenSans-SemiBold.ttf"),
  });
